// ─────────────────────────────────────────────────────────────
// LETRADO — words.js
// GAME_WORDS  → palavras sorteadas (sem acento, 5 letras)
// VALID_WORDS → todas aceitas como tentativa
// Versão: 0.1.3
// ─────────────────────────────────────────────────────────────

const GAME_WORDS = [
  "abrir","acaso","aceno","aceso","acima","adeus","adiar","afeto","afoga","agora",
  "agudo","ajuda","alado","alamo","algar","algum","alhos","aliar","aloca","aloja",
  "altar","aluno","amado","amara","amaro","ameba","amena","ameno","amigo","amora",
  "andar","anelo","anima","animo","antes","anzol","apelo","apito","apoio","arara",
  "arcar","ardor","areia","armar","aroma","arras","arroz","artes","assar","atira",
  "atola","atona","atura","audaz","avaro","aveia","aviso","avoar","azedo",
  "babao","baixo","banco","banda","bando","banho","barco","barro","bater","beber",
  "beijo","beira","berco","bicho","bingo","bloco","blusa","bocal","bolas","bolso",
  "bomba","bonde","bordo","braco","bravo","breve","briga","brisa","broto","bruma",
  "bumbo","bambu","baiao","bodas","burro","busto","capuz",
  "caber","cabra","cacar","cacho","caldo","calha","calma","calmo","calor","campo",
  "canal","capaz","carne","carro","carta","casca","casco","casas","catar","causa",
  "cavar","ceder","ceifa","celar","cento","cerca","cerco","certo","chave","cheio",
  "chuva","cinco","circo","cisne","cobra","cocar","coisa","colmo","comer","conde",
  "corar","coroa","corpo","corno","corte","coser","costa","couro","couve","covil",
  "coxia","credo","crime","crivo","crise","cueca","culpa","cunha","cupim","curso",
  "curto","caqui","cerol","ciume","corja",
  "danca","dardo","datar","denso","desde","dever","diabo","dieta","disco","ditar",
  "doces","doido","domar","dorso","drama","dueto","duplo",
  "ebano","edema","ereto","espia","estar","etapa","etnia","exame","expor","extra",
  "facil","facao","faina","falar","falha","falta","fardo","farra","fatal","favor",
  "febre","feito","feliz","femea","fenda","feroz","ferro","festa","ficar","filho",
  "final","fisco","fitar","floco","fonte","forca","forma","forno","forte","fosco",
  "fraco","fraga","frear","freio","frevo","fruta","fundo","furar","fusao","fuzil",
  "furia","fuzue",
  "ganha","garbo","garca","garfo","garra","gasto","gatos","gelar","genio","girar",
  "globo","glosa","gordo","graca","grama","greve","grilo","gripe","gruta","guiar",
  "heroi","hiato","hinos","honra","horto","hotel","humor",
  "ideia","igual","ilhar","imune","indio","ineto","inova","irada",
  "jarro","jeito","jogar","juizo","junto","jurar","jovem",
  "lacre","lacos","ladro","largo","laser","laudo","lavar","lebre","legal","leigo",
  "leite","lento","leque","letra","lindo","linha","lista","litro","livro","local",
  "lombo","longe","lorde","louca","louvo","lutar","lutas",
  "macho","macio","magoa","maior","manga","manta","manso","manto","marca","massa",
  "matar","medir","meiga","melao","menor","menta","mesma","mesmo","metro","mexer",
  "miado","miolo","mirar","mirra","missa","minto","moeda","molde","morar","morsa",
  "morte","morto","mosca","motel","motor","mouro","mouse","multa","mundo","murro",
  "nadar","nariz","nacao","navio","negro","nobre","noite","norma","nuvem",
  "obeso","ocaso","odiar","olhar","ondas","opera","optar","ordem","orgao","ousar",
  "outro",
  "pacto","padre","parar","pardo","parir","parra","parte","parto","pasta","patio",
  "pausa","pedra","pegar","peito","penal","pente","perda","persa","perto","pesar",
  "picar","pilha","pinha","pires","pizza","plano","pleno","pobre","poder","poema",
  "polvo","pomar","ponte","porta","posse","posto","praia","prata","prazo","presa",
  "preso","prima","primo","preto","preta","prova","pudim","pulso","puxar","penis",
  "pinto","porno","prato",
  "racao","ralar","ramos","rapaz","raspa","rasto","razao","redor","refem","regra",
  "relva","renda","resto","retro","reves","rezar","rindo","rival","rodar","rolha",
  "rombo","ronco","rosca","rosto","rotor","roupa","roubo","rumar","rural",
  "saber","sacar","salsa","salto","salvo","samba","santa","sarda","secar","sedas",
  "senha","setor","sigla","silvo","sirva","sobre","solar","sopro","sorte","solta",
  "suave","sumir","supor","surdo","surto","sabao","sabor","salao","sexto","subir",
  "sujar",
  "tacho","talco","tanto","tapas","tarde","tarso","taxar","tedio","temer","tempo",
  "tenda","tenso","terra","tesao","tigre","timao","tirar","tocar","tomar","tonel",
  "torca","torco","torto","total","touca","traco","trama","travo","troco","trova",
  "truco","tumor","turma",
  "unico","uniao","usina",
  "vagar","vapor","vario","vasto","veado","venda","vento","verde","verso","vigor",
  "virar","viver","vodka","votar","vulto","vazio","vinho",
  "zebra","zinco","zomba","zunir","zurro",
  "oxala","lepra","gorro","gozar","coito","moita","bolos","bunda","coxas","loiro",
  "loira","morno","gordo","magro","calmo","chuva","campo","bruta","bruto","cinza",
  "fugir","lutar","fumar","morar","casar","botar","bravo","novos","roxos","roxas",
  "verme","horto",
  "cursa","ombro","sorri","chora","grita","pular","beija","botao","fecho","cinto",
  "meias","feijo","milho","trigo","fazer","dizer","ligar","ouvir","golpe","saque",
  "lance","passe","chute","tenis","aviao","serra","norte","leste","oeste","praca",
  "torta","limao","peixe","times","selva","mares",
  // v0.1.2
  "cromo","coral","moral","banal","porca","porco","horas","noras","genro","marco",
  "abril","maios","julho","junho","besta","retas",
].filter((w,i,a) => w.length === 5 && a.indexOf(w) === i);

// ─── VALID_WORDS ──────────────────────────────────────────────
const VALID_WORDS = new Set([
  ...GAME_WORDS,
  "abaco","abada","abafo","abalo","abana","abano","abate","abeto","aboca","aboio",
  "abona","abono","abriu","abusa","acaba","acabe","acado","acara","acari","acaro",
  "acata","acate","acebo","aceda","acede","acedo","aceia","acera","acerb","acere",
  "acero","acesa","aceta","aceto","achar","achei","achou","acida","acide","acido",
  "acina","acino","acita","acode","acoes","acofa","acoia","acola","acoma","acona",
  "acone","acono","acopa","acore","acoro","acosa","acoso","acota","acote","acoto",
  "acova","acovo","acuar","acuda","acude","acudo","acuia","acuir","acure","acuro",
  "acusa","acuse","acuso","adaga","adagi","adago","adail","adais","adele","ademi",
  "adena","adeno","adere","aderi","adero","adiai","adiam","adias","adica","adido",
  "adiga","adige","adigo","adijo","adila","adimo","adina","adino","adipa","adipo",
  "adira","adire","adiri","adiro","adita","adite","adito","adiva","adive","adivo",
  "adobe","adoca","adoco","adoes","adoga","adogo","adola","adole","adolo","adoma",
  "adome","adomo","adona","adone","adono","adopa","adope","adopo","adore","adori",
  "adoro","adota","adote","adoto","adova","adove","adovo","adubo","aduco","adufe",
  "adula","adulo","aduma","adume","adumo","aduna","adune","aduno","adure","aduri",
  "aduro","adusa","aduso","adust","aduto","afago","afana","afano","afiar","afina",
  "afine","afino","afora","afore","aforo","afuga","afumo","agave","agiam","agiar",
  "agias","agido","agimo","agios","agira","agita","agite","agito","agnar","agoes",
  "agras","agria","agrio","agros","aguar","aguda","agula","aguro","aguta","aguto",
  "ainda","aiola","aione","aioni","aiora","aioto","ajuga","ajumo","alada","alaga",
  "alago","alaia","alaio","alais","alame","alana","alano","alapa","alara","alare",
  "alari","alaro","alata","alate","alato","alave","alavo","albas","album","alcar",
  "alcoa","aldea","aleia","aleis","aleja","aleje","alejo","alela","alele","aleli",
  "alelo","alema","alemo","alena","aleno","alepa","alepe","alepo","alera","alere",
  "aleri","alero","aleta","alete","aleto","aleva","aleve","alevo","alfar","alfas",
  "algaz","algoz","aliai","alias","alibi","alica","alice","alico","alida","alido",
  "alifa","alifo","aliga","aligo","alija","alije","alijo","alila","alile","alilo",
  "alima","alime","alimo","alina","aline","alino","alipa","alipe","alipo","alira",
  "alire","aliri","aliro","alisa","alise","aliso","alita","alite","alito","aliva",
  "alive","alivo","almar","almas","almei","almos","aloes","alofe","alofo","aloma",
  "alome","alomo","alona","alone","alono","alopa","alope","alopo","alora","alore",
  "alori","aloro","alosa","alose","aloso","alota","alote","aloto","alova","alove",
  "alovo","aluca","aluco","aluda","alude","aludi","aludo","aluga","alugo","aluia",
  "aluir","aluis","aluma","alume","alumo","aluna","alune","alura","alure","aluri",
  "aluro","alusa","aluse","aluso","aluta","alute","aluto","aluva","aluve","aluvo",
  "amais","amala","amale","amali","amalo","amamo","amana","amane","amano","amapa",
  "amasa","amase","amaso","amata","amate","amato","amava","amave","amavo","ambas",
  "ambos","ameia","ameio","ameis","ameja","ameje","amejo","amela","amele","ameli",
  "amelo","amema","ameme","amemo","amepa","amepe","amepo","amera","amere","ameri",
  "amero","amesa","amese","ameso","ameta","amete","ameto","ameva","ameve","amevo",
  "amiam","amiar","amias","amica","amico","amida","amide","amido","amiga","amija",
  "amije","amijo","amila","amile","amilo","amima","amime","amimo","amina","amine",
  "amino","amipa","amipe","amipo","amire","amiri","amiro","amisa","amise","amiso",
  "amita","amite","amito","amiva","amive","amivo","amnio","amoca","amode","amodo",
  "amoes","amofa","amofo","amoga","amogo","amoia","amoie","amoio","amois","amoja",
  "amoje","amojo","amola","amole","amoli","amolo","amoma","amome","amomo","amona",
  "amone","amono","amopa","amope","amopo","amore","amori","amoro","amosa","amose",
  "amoso","amota","amote","amoto","amova","amove","amovi","amovo","ampla","amplo",
  "anago","anais","anata","aneis","anema","anemo","aneto","anevo","angra","angue",
  "anjos","aonde","antro","apora","apose","aposo","apraz","apura","apure","apuro",
  "arena","arete","arido","arque","arvor","assen","assis","assom","assos","ateal",
  "ateus","ature","aturo","ambar","aipim","axila","casar","aureo",
  "bacar","baldo","belas","belga","belos","bosco","buzio","calca","caros","cavoa",
  "clame","clamo","curau","cacoa","cisao","clone","clube","cofre","dobra","dobro",
  "donos","ebrio","educa","elege","eleva","emita","ensai","entra","etano","evade",
  "exato","falso","fanfa","farpa","farsa","fauna","fervo","fisga","flama","flora",
  "fluxo","forja","garoa","junco","magoa","nervo","ovulo","orlas","papel","pavao",
  "pavor","perna","pelve","pedal","pomba","pombo","sofra","sorvo","teima","tiara",
  "valor","valsa","velha","velho","viela","jesus","ebola",
]);

// ─── Validação automática no console do navegador ─────────────
(function checar() {
  const erros = [];
  const tudo = [...new Set([...GAME_WORDS, ...VALID_WORDS])];
  tudo.forEach(w => {
    const limpa = w.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    if (limpa.length !== 5) erros.push(`"${w}" → ${limpa.length} letras`);
  });
  if (erros.length) {
    console.error("❌ PALAVRAS COM TAMANHO ERRADO:", erros);
  } else {
    console.log(`✅ words.js OK — v0.1.2 | ${GAME_WORDS.length} sorteáveis | ${VALID_WORDS.size} aceitas`);
  }
})();
